# Generated by Django 2.2.4 on 2019-08-29 16:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import jats.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=jats.core.models.default_settings),
        ),
    ]
